kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: aditapi
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: aditapi
    spec:
      containers:
      - name: aditapi
        image: gcr.io/mitlib-adit/aditapi:0.1
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres
                key: password
        ports:
          - containerPort: 4000
            name: http
            protocol: TCP
