kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: elasticsearch
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: elasticsearch:2
        ports:
          - containerPort: 9200
            name: http
            protocol: TCP
