kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: fedora
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: repository
    spec:
      containers:
        - name: fedora
          image: gcr.io/mitlib-adit/fedora:4.7.0.1
          volumeMounts:
            - mountPath: /fcrepo4-data
              name: fedora-store
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 61613
              name: stomp
              protocol: TCP
      volumes:
        - name: fedora-store
          gcePersistentDisk:
            pdName: fedora-store
            fsType: ext4
