kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: nginx-proxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: proxy
    spec:
      containers:
        - name: nginx
          image: gcr.io/mitlib-adit/nginx-proxy:0.1.0
          env:
            - name: FEDORA_USER
              valueFrom:
                secretKeyRef:
                  name: fedora
                  key: username
            - name: FEDORA_PASS
              valueFrom:
                secretKeyRef:
                  name: fedora
                  key: password
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
